spring:
  application:
    name: market-vision
  
  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s
    rest-client:
      read-timeout: 30s
  
  # 数据库配置
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/marketvision?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1008610086
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  ai:
    openai:
      api-key: sk-7f9Ww05vQRwWJuAJAF7FFQAnMTm3VBWBIr4IQQrYVmBe2flc
      base-url: https://max.brother99.top/v1
      chat:
        options:
          model: "[满血伪流]gemini-2.5-pro-search"
    vertex:
      ai:
        gemini:
          enabled: false
    anthropic:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vertexai.gemini.VertexAiGeminiAutoConfiguration
      - org.springframework.ai.autoconfigure.anthropic.AnthropicAutoConfiguration

# 服务器配置
server:
  port: 8091
  servlet:
    context-path: /api

# 日志配置 - 输出到 Elasticsearch
logging:
  level:
    org.springframework: DEBUG
    com.gigass: DEBUG
    com.gigass.trading.repository: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
debug: true

# 热搜采集配置
hotsearch:
  crawler:
    weibo:
      url: https://s.weibo.com/top/summary
      interval: 600000  # 10分钟
    baidu:
      url: https://top.baidu.com/board?tab=realtime
      interval: 600000  # 10分钟
    zhihu:
      url: https://www.zhihu.com/hot
      interval: 600000  # 10分钟

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 雪花算法配置
snowflake:
  worker-id: 1      # 工作机器ID (0-31)
  datacenter-id: 1  # 数据中心ID (0-31)

# Demo 控制开关
demo:
  lifecycle:
    enabled: false  # 设为 true 时启用
