spring:
  application:
    name: market-vision
  
  # 数据库配置
  datasource:
    # 默认使用H2内存数据库，便于开发和测试
    url: jdbc:h2:mem:marketvision;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    # 如需切换到MySQL，取消下面的注释并注释上面的H2配置
    # url: jdbc:mysql://localhost:3306/marketvision?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    # username: root
    # password: root
    # driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        # MySQL方言，切换到MySQL时使用
        # dialect: org.hibernate.dialect.MySQL8Dialect
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      # password: 
      database: 0
  
  # AI模型配置
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      model: gpt-4-turbo-preview
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:your-api-key}
      model: claude-3-opus-20240229
    vertex-ai:
      project-id: ${VERTEX_AI_PROJECT_ID:your-project-id}
      location: ${VERTEX_AI_LOCATION:us-central1}
      model: gemini-1.5-pro

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    root: INFO
    com.gigass: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  file:
    name: logs/market-vision.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 热搜采集配置
hotsearch:
  crawler:
    weibo:
      url: https://s.weibo.com/top/summary
      interval: 600000  # 10分钟
    baidu:
      url: https://top.baidu.com/board?tab=realtime
      interval: 600000  # 10分钟
    zhihu:
      url: https://www.zhihu.com/hot
      interval: 600000  # 10分钟

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
