spring:
  application:
    name: market-vision
  
  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s
    rest-client:
      read-timeout: 30s
  
  # 数据库配置
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/marketvision?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1008610086
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  ai:
    openai:
      api-key: xxxx
      base-url: https://max.brother99.top
      chat:
        options:
          model: "[100k]gemini-2.5-pro"
    vertex:
      ai:
        gemini:
          enabled: false
    anthropic:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vertexai.gemini.VertexAiGeminiAutoConfiguration
      - org.springframework.ai.autoconfigure.anthropic.AnthropicAutoConfiguration

# 服务器配置
server:
  port: 8091
  servlet:
    context-path: /api

# 日志配置 - 减少控制台输出
logging:
  config: classpath:logback-spring.xml
  level:
    com.gigass: DEBUG
    org.springframework: INFO
    org.elasticsearch: WARN
    org.apache.http: WARN
  file:
    path: logs

# 热搜采集配置
hotsearch:
  crawler:
    base-url: http://localhost:6688
    platforms:
      - douyin
      - weibo
      - baidu
    cache: false
    interval: 600000  # 10分钟

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 雪花算法配置
snowflake:
  worker-id: 1      # 工作机器ID (0-31)
  datacenter-id: 1  # 数据中心ID (0-31)

# Demo 控制开关
demo:
  lifecycle:
    enabled: false
  ai:
    enabled: true