spring:
  application:
    name: market-vision
  
  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s
    rest-client:
      read-timeout: 30s
  
  # 数据库配置
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/marketvision?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1008610086
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  ai:
    openai:
      api-key: sk-7f9Ww05vQRwWJuAJAF7FFQAnMTm3VBWBIr4IQQrYVmBe2flc
      base-url: https://max.brother99.top
      chat:
        options:
          model: "[满血伪流]gemini-2.5-pro-search"
    vertex:
      ai:
        gemini:
          enabled: false
    anthropic:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vertexai.gemini.VertexAiGeminiAutoConfiguration
      - org.springframework.ai.autoconfigure.anthropic.AnthropicAutoConfiguration

# 服务器配置
server:
  port: 8091
  servlet:
    context-path: /api

# 日志配置 - 减少控制台输出
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gigass: INFO
    com.gigass.trading.repository: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.springframework.boot.autoconfigure: WARN
    org.springframework.beans.factory: WARN
    com.internetitem.logback.elasticsearch: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{20} - %msg%n"
debug: false

# 热搜采集配置
hotsearch:
  crawler:
    weibo:
      url: http://localhost:6688/weibo
      interval: 600000  # 10分钟
    baidu:
      url: http://localhost:6688/baidu
      interval: 600000  # 10分钟
    zhihu:
      url: http://localhost:6688/zhihu
      interval: 600000  # 10分钟

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 雪花算法配置
snowflake:
  worker-id: 1      # 工作机器ID (0-31)
  datacenter-id: 1  # 数据中心ID (0-31)

# Demo 控制开关
demo:
  lifecycle:
    enabled: false  # 设为 true 时启用
